[phases.setup]
nixPkgs = ["nodejs", "chromium", "fontconfig", "tzdata"]

[phases.build]
cmds = ["npm ci"]

[start]
cmd = "node src/index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
TZ = "Asia/Seoul"
